# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: "Home"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: "Australia/Brisbane"
  unit_system: metric
  packages: !include_dir_named packages

# Custom history
# home-assistant.io/integrations/history
recorder:
  exclude:
    entities:
      - sensor.brisbane_city_train
      - sensor.beenleigh_train

      # Helper entities
      - binary_sensor.livingroom_dashboard1_motion
      - binary_sensor.ubpx700_ping
      - binary_sensor.dashboard1_ping
      - sensor.watchman_last_updated
      - light.adaptive_lighting
      - light.timer_lights
      - switch.livingroom_hifi_fan
      - switch.masterbedroom_fan
      - select.livingroom_dashboard1_page
      - switch.livingroom_dashboard1_power
    entity_globs:
      - automation.*
      - weather.*
      - script.*

# Enable OTA updates for ZHA
# home-assistant.io/integrations/zha
zha:
  zigpy_config:
    ota:
      ikea_provider: true
      otau_directory: /partials/zigpy_ota

# Adjust light temperature throughout the day
# github.com/basnijholt/adaptive-lighting
adaptive_lighting:
  lights:
    - light.adaptive_lighting
  sleep_brightness: 1
  sleep_color_temp: 2200

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
