substitutions:
  name: esphome-web-fd1346
  friendly_name: desk-control

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: d1_mini

output:
  - platform: gpio
    pin: D1
    id: led_relay
  - platform: gpio
    pin: D2
    id: desk_fan

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D4
    num_leds: 60
    name: "Monitor Light"
    on_turn_on:
      - output.turn_on: led_relay
    on_turn_off:
      - output.turn_off: led_relay

fan:
  - platform: template
    restore_mode: ALWAYS_OFF
    name: "Desk Fan"
    on_state:
      - output.turn_on: desk_fan

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Esphome-Web-fd1346'
    password: !secret wifi_fallback

captive_portal: