esphome:
  name: esphome-web-b94825
  friendly_name: door-chime

esp8266:
  board: d1_mini

# Enable logging
logger:

# Assign solenoids as outputs.
output:
  - platform: gpio
    pin: D1
    id: striker_1
  - platform: gpio
    pin: D2
    id: striker_2

button:
  - platform: output
    id: doorbell_1
    name: "Doorbell Striker 1"
    output: striker_1
    duration: 250ms
  - platform: output
    id: doorbell_2
    name: "Doorbell Striker 2"
    output: striker_2
    duration: 250ms

  # Template button for 'front door' chime
  - platform: template
    name: "Doorbell"
    on_press:
      then:
       - button.press: doorbell_1
       - delay: 500ms
       - button.press: doorbell_2

# Enable Home Assistant API
api:
  encryption:
    key: !secret chime_key

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-B94825"
    password: !secret wifi_fallback

captive_portal:
    